### ISSUE TITLE
npm install fails for pngout-bin

### ISSUE THREAD

**Issue by honrust** [imagemin/pngout-bin#2]
I am getting the following "npm install" error on pngout-bin. This dependency is inserted because I am trying to use "ionic-minify" in an ionic app project. Could there be some kind of dependency problem? I did not modify any of the version numbers...

```
> pngout-bin@2.0.1 postinstall C:\dev\ad6\node_modules\pngout-bin
> node lib/install.js

module.js:339
    throw err;
    ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\dev\ad6\node_modules\pngout-bin\node_modules\imagemin-log\node_modules\squeak\index.js:5:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\dev\\tools\\nodejs\\node.exe" "C:\\dev\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! pngout-bin@2.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngout-bin@2.0.1 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the pngout-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pngout-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ad6\npm-debug.log
```

**Comment by shinnn** [comment]
1. You're using older Node and npm. Upgrade both to the latest stable version.
2. Can you try pngout-bin v3.0.0? `npm install pngout-bin@3.0.0`

**Comment by shinnn** [comment]
Totally no feedback.

**Comment by Alexintosh** [comment]
I have the same issue, unfortunately I cannot update to a newer version of npm/node because ionic is meant to work with v0.12.7

**Comment by vindia** [comment]
The error disappears when installing v3.0.0 :)

**Comment by Alexintosh** [comment]
+1

**Comment by shinnn** [comment]
@Alexintosh Deleted the last comment. All the uninformative +1 comments are meaningless for the maintainers. https://github.com/dear-github/dear-github

**Comment by laoyipay** [comment]
@shinnn  Thanks for your answer, installing v3.0.0 solved the problem

**Comment by thomashrabe** [comment]
v3.0.0 solved it @shinnn
