### ISSUE TITLE
[postinstall] ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by pavelloz** [imagemin/pngout-bin#5]
Hello,

Im trying to install imageoptim, but for some reason pngout-bin is throwing in postinstall stage.

Any ideas how to fix it/skip pngout without going back to node 11 which is very old?

I found: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

Which suggests upgrading `graceful-fs`, which i think would be the best solution for the future, considering node v14 just came out.

ENV:
```
macos 10.14.6
node 12.16.1
npm 6.13.1
imageoptim - latest
pngout-bin@2.0.1
```

```
posify|master⚡ ⇒ npm i --save imageoptim       

fs.js:35
} = primordials;
    ^
ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/Users/pavel/projects/posify/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/pavel/projects/posify/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/pavel/projects/posify/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
```

**Comment by pavelloz** [comment]
Nevermind, i think this is the wrong place for this issue. :)
